import { useMemo, useState } from "react";
import { Check, Clipboard, Code2, Eye, EyeOff, KeyRound, Plus, RefreshCcw, SearchX, ShieldCheck, Trash2, Webhook } from "lucide-react";
import { toast } from "sonner";
import { buttonClass, controlClass, EmptyState, IconButton, Modal, PageHeader, Panel, primaryButtonClass, SearchField, Stat, StatusBadge, Toggle } from "./_shared";

type ApiKey = { id: string; name: string; prefix: string; scopes: string[]; created: string; lastUsed: string; expires: string; status: "active" | "revoked" };
const seed: ApiKey[] = [
  { id: "key1", name: "CI production deploys", prefix: "orb_live_8fd2••••••••b91c", scopes: ["deployments:write", "servers:read"], created: "May 12, 2026", lastUsed: "3 minutes ago", expires: "Never", status: "active" },
  { id: "key2", name: "Metrics exporter", prefix: "orb_live_61aa••••••••c0d8", scopes: ["monitoring:read"], created: "Mar 2, 2026", lastUsed: "1 hour ago", expires: "Mar 2, 2027", status: "active" },
  { id: "key3", name: "Legacy deploy bot", prefix: "orb_test_40bd••••••••1aa2", scopes: ["deployments:write"], created: "Jan 4, 2026", lastUsed: "2 months ago", expires: "Expired", status: "revoked" },
];

export function ApiKeysPage() {
  const [keys, setKeys] = useState(seed);
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [secret, setSecret] = useState("");
  const [show, setShow] = useState(false);
  const [draft, setDraft] = useState({ name: "", expiry: "365 days", write: false });
  const filtered = useMemo(() => keys.filter((x) => `${x.name} ${x.prefix} ${x.scopes.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [keys, query]);

  function create() { if (!draft.name.trim()) return toast.error("Key name is required"); const raw = `orb_live_${crypto.randomUUID().replaceAll("-", "")}`; setSecret(raw); setShow(true); setKeys((x) => [{ id: `key_${Date.now()}`, name: draft.name, prefix: `${raw.slice(0, 13)}••••••••${raw.slice(-4)}`, scopes: draft.write ? ["servers:read", "files:write", "deployments:write"] : ["servers:read", "monitoring:read"], created: "Just now", lastUsed: "Never", expires: draft.expiry, status: "active" }, ...x]); toast.success("API key created"); }

  return <div className="space-y-5">
    <PageHeader eyebrow="Developer platform" title="API keys" description="Create scoped credentials for CI, internal tools, and direct access to the Orbit API." actions={<button className={primaryButtonClass} onClick={() => { setOpen(true); setSecret(""); setDraft({ name: "", expiry: "365 days", write: false }); }}><Plus className="size-3.5" />Create API key</button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Active keys" value={keys.filter((x) => x.status === "active").length} detail="Across 2 environments" icon={KeyRound} /><Stat label="Requests this month" value="84.2k" detail="0.04% error rate" icon={Code2} tone="sky" /><Stat label="Security" value="Scoped" detail="Keys are hashed at rest" icon={ShieldCheck} tone="emerald" /></div>
    <Panel title="Workspace API keys" description="Secrets are shown once and cannot be recovered" flush><div className="border-b border-white/[0.06] p-3"><SearchField value={query} onChange={setQuery} placeholder="Search keys and scopes" /></div>{filtered.length ? <div className="divide-y divide-white/[0.06]">{filtered.map((key) => <div key={key.id} className="grid gap-3 px-4 py-4 lg:grid-cols-[minmax(0,1fr)_minmax(200px,1fr)_150px_110px_auto] lg:items-center"><div><div className="flex items-center gap-2"><p className="text-sm font-medium text-zinc-200">{key.name}</p><StatusBadge status={key.status} /></div><p className="mt-1 font-mono text-[10px] text-zinc-600">{key.prefix}</p></div><div className="flex flex-wrap gap-1">{key.scopes.map((scope) => <span key={scope} className="rounded-md border border-white/[0.07] bg-white/[0.025] px-2 py-1 font-mono text-[9px] text-zinc-500">{scope}</span>)}</div><div className="text-[10px]"><p className="text-zinc-400">Used {key.lastUsed}</p><p className="mt-1 text-zinc-600">Created {key.created}</p></div><span className="text-[10px] text-zinc-500">Expires {key.expires}</span><div className="flex justify-end">{key.status === "active" ? <><IconButton title="Rotate key" onClick={() => toast.info("Create a replacement key, update clients, then revoke this key") }><RefreshCcw className="size-3.5" /></IconButton><IconButton title="Revoke" onClick={() => { setKeys((rows) => rows.map((x) => x.id === key.id ? { ...x, status: "revoked" } : x)); toast.success("API key revoked"); }}><Trash2 className="size-3.5" /></IconButton></> : null}</div></div>)}</div> : <EmptyState icon={SearchX} title="No API keys found" description="Create a scoped key or change your search." />}</Panel>
    <Panel title="API quick start" description="Send an authenticated request to list servers"><div className="relative rounded-lg border border-white/[0.07] bg-black/30 p-4"><button className="absolute right-3 top-3 grid size-7 place-items-center rounded-md bg-white/[0.05] text-zinc-500" onClick={() => { navigator.clipboard.writeText("curl https://api.orbit.dev/v1/servers -H 'Authorization: Bearer $ORBIT_API_KEY'"); toast.success("Example copied"); }}><Clipboard className="size-3.5" /></button><pre className="overflow-x-auto text-[11px] leading-6 text-emerald-300">curl https://api.orbit.dev/v1/servers \<br />  -H 'Authorization: Bearer $ORBIT_API_KEY'</pre></div><div className="mt-3 flex gap-2"><button className={buttonClass} onClick={() => toast.info("API documentation opened")}>Read API docs</button><button className={buttonClass} onClick={() => toast.info("Webhook documentation opened")}><Webhook className="size-3" />Webhooks</button></div></Panel>
    <Modal open={open} onClose={() => setOpen(false)} title={secret ? "Save your API key" : "Create API key"} description={secret ? "Copy this secret now. For security, it will never be shown again." : "Give the key the least privilege and shortest useful lifetime."} footer={secret ? <button className={primaryButtonClass} onClick={() => setOpen(false)}><Check className="size-3.5" />I saved the key</button> : <><button className={buttonClass} onClick={() => setOpen(false)}>Cancel</button><button className={primaryButtonClass} onClick={create}>Create key</button></>}>{secret ? <div><div className="flex items-center gap-2 rounded-lg border border-emerald-400/20 bg-emerald-400/[0.05] p-3"><code className="min-w-0 flex-1 break-all text-xs text-emerald-200">{show ? secret : secret.replace(/.(?=.{4})/g, "•")}</code><IconButton title="Show or hide" onClick={() => setShow(!show)}>{show ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}</IconButton><IconButton title="Copy key" onClick={() => { navigator.clipboard.writeText(secret); toast.success("API key copied"); }}><Clipboard className="size-3.5" /></IconButton></div><p className="mt-3 text-[10px] leading-5 text-zinc-500">Store it in a secrets manager. Never commit this value to source control or include it in client-side code.</p></div> : <div className="space-y-4"><label className="text-xs text-zinc-400">Key name<input autoFocus className={`${controlClass} mt-1.5 w-full`} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="CI deploy runner" /></label><label className="text-xs text-zinc-400">Expiration<select className={`${controlClass} mt-1.5 w-full`} value={draft.expiry} onChange={(e) => setDraft({ ...draft, expiry: e.target.value })}><option>30 days</option><option>90 days</option><option>365 days</option><option>Never</option></select></label><div className="flex items-center justify-between rounded-lg border border-white/[0.07] p-3"><div><p className="text-xs font-medium text-zinc-300">Write access</p><p className="mt-1 text-[10px] text-zinc-600">Allow file changes and deployments</p></div><Toggle checked={draft.write} onChange={(write) => setDraft({ ...draft, write })} label="Write access" /></div></div>}</Modal>
  </div>;
}

export const APIKeysPage = ApiKeysPage;
export default ApiKeysPage;
