import { useMemo, useState } from "react";
import { Blocks, CheckCircle2, CircleDot, Cloud, Github, Globe2, MessageSquare, Plus, SearchX, Send, Settings2, Slack, Unplug, Webhook, Workflow } from "lucide-react";
import { toast } from "sonner";
import type { LucideIcon } from "lucide-react";
import { buttonClass, controlClass, EmptyState, Modal, PageHeader, Panel, primaryButtonClass, SearchField, Stat, StatusBadge } from "./_shared";

type Integration = { id: string; name: string; description: string; category: string; connected: boolean; icon: LucideIcon; color: string; detail?: string };
const catalog: Integration[] = [
  { id: "github", name: "GitHub", description: "Deploy from repositories and attach commit metadata.", category: "Source control", connected: true, icon: Github, color: "text-zinc-100", detail: "acme-engineering · 8 repos" },
  { id: "slack", name: "Slack", description: "Route deploy, backup, and incident notifications.", category: "Communication", connected: true, icon: Slack, color: "text-fuchsia-300", detail: "#platform-ops" },
  { id: "sentry", name: "Sentry", description: "Correlate releases with errors and regressions.", category: "Observability", connected: false, icon: CircleDot, color: "text-violet-300" },
  { id: "aws", name: "AWS", description: "Discover instances and use KMS-backed secrets.", category: "Cloud", connected: true, icon: Cloud, color: "text-amber-300", detail: "us-east-1 · role/orbit" },
  { id: "discord", name: "Discord", description: "Deliver lightweight operational notifications.", category: "Communication", connected: false, icon: MessageSquare, color: "text-indigo-300" },
  { id: "webhook", name: "Custom webhook", description: "Send signed JSON events to any HTTPS endpoint.", category: "Developer tools", connected: false, icon: Webhook, color: "text-sky-300" },
];

export function IntegrationsPage() {
  const [items, setItems] = useState(catalog);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [selected, setSelected] = useState<Integration>();
  const [webhooks, setWebhooks] = useState([{ id: "wh1", url: "https://hooks.acme.dev/orbit/events", events: "deploy.*, backup.failed", status: "active", lastDelivery: "17 min ago" }]);
  const filtered = useMemo(() => items.filter((x) => (category === "all" || x.category === category) && `${x.name} ${x.description}`.toLowerCase().includes(query.toLowerCase())), [items, query, category]);
  const categories = [...new Set(items.map((x) => x.category))];

  function toggle(item: Integration) { setItems((rows) => rows.map((x) => x.id === item.id ? { ...x, connected: !x.connected, detail: x.connected ? undefined : "Connected just now" } : x)); setSelected(undefined); toast.success(item.connected ? `${item.name} disconnected` : `${item.name} connected`); }

  return <div className="space-y-5">
    <PageHeader eyebrow="Ecosystem" title="Integrations" description="Connect source control, clouds, observability, and communication tools to your server workflows." actions={<button className={buttonClass} onClick={() => toast.info("Integration request sent to the Orbit team")}><Plus className="size-3.5" />Request integration</button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Connected apps" value={items.filter((x) => x.connected).length} detail="All connections healthy" icon={Blocks} /><Stat label="Events delivered" value="18.4k" detail="99.99% success this month" icon={Send} tone="emerald" /><Stat label="Active webhooks" value={webhooks.length} detail="Signed with SHA-256" icon={Webhook} tone="sky" /></div>
    <Panel title="Integration catalog" description="Extend your workspace with trusted services" flush><div className="grid gap-2 border-b border-white/[0.06] p-3 sm:grid-cols-[minmax(0,1fr)_190px]"><SearchField value={query} onChange={setQuery} placeholder="Search integrations" /><select value={category} onChange={(e) => setCategory(e.target.value)} className={controlClass}><option value="all">All categories</option>{categories.map((x) => <option key={x}>{x}</option>)}</select></div>{filtered.length ? <div className="grid gap-3 p-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className="rounded-xl border border-white/[0.07] bg-black/10 p-4"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.03] ${item.color}`}><item.icon className="size-5" /></span><StatusBadge status={item.connected ? "active" : "available"} /></div><h3 className="mt-4 text-sm font-semibold text-zinc-100">{item.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-zinc-500">{item.description}</p>{item.detail ? <p className="mt-3 truncate rounded-lg bg-white/[0.025] px-2.5 py-2 text-[10px] text-zinc-500">{item.detail}</p> : <div className="mt-3 h-8" />}<button className={`${item.connected ? buttonClass : primaryButtonClass} mt-4 w-full`} onClick={() => setSelected(item)}>{item.connected ? <><Settings2 className="size-3" />Manage</> : <><Globe2 className="size-3" />Connect</>}</button></article>)}</div> : <EmptyState icon={SearchX} title="No integrations found" description="Try another name or category." />}</Panel>
    <Panel title="Webhooks" description="Signed outbound events to your own systems" actions={<button className={primaryButtonClass} onClick={() => { setWebhooks((x) => [...x, { id: `wh_${Date.now()}`, url: "https://example.com/orbit", events: "server.offline", status: "active", lastDelivery: "Never" }]); toast.success("Webhook endpoint created"); }}><Plus className="size-3" />Add endpoint</button>} flush>{webhooks.length ? <div className="divide-y divide-white/[0.06]">{webhooks.map((hook) => <div key={hook.id} className="grid gap-3 px-4 py-4 md:grid-cols-[minmax(0,1fr)_200px_100px_auto] md:items-center"><div><p className="truncate font-mono text-xs text-zinc-300">{hook.url}</p><p className="mt-1 text-[10px] text-zinc-600">Events: {hook.events}</p></div><span className="text-[10px] text-zinc-500">Last delivery {hook.lastDelivery}</span><StatusBadge status={hook.status} /><button className={buttonClass} onClick={() => toast.success("Test event delivered in 182ms")}><Send className="size-3" />Test</button></div>)}</div> : null}</Panel>
    <Modal open={Boolean(selected)} onClose={() => setSelected(undefined)} title={selected?.name ?? "Integration"} description={selected?.connected ? "Connection credentials are encrypted and can be revoked at any time." : "You will be redirected to authorize this connection."}>{selected ? <div className="space-y-4"><div className="flex items-center gap-3 rounded-lg border border-white/[0.07] bg-black/10 p-4"><span className={`grid size-10 place-items-center rounded-xl bg-white/[0.04] ${selected.color}`}><selected.icon className="size-5" /></span><div><p className="text-sm font-medium text-zinc-200">{selected.name}</p><p className="text-[10px] text-zinc-500">{selected.connected ? selected.detail : "Not connected"}</p></div></div>{selected.connected ? <><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-400">Event scope<select className={`${controlClass} mt-1.5 w-full`}><option>All workspace events</option><option>Deployment events</option><option>Alerts only</option></select></label><label className="text-xs text-zinc-400">Default destination<input className={`${controlClass} mt-1.5 w-full`} defaultValue={selected.detail ?? "Default"} /></label></div><div className="flex gap-2"><button className={buttonClass} onClick={() => toast.success("Integration settings saved")}><CheckCircle2 className="size-3" />Save settings</button><button className={buttonClass} onClick={() => toggle(selected)}><Unplug className="size-3" />Disconnect</button></div></> : <button className={`${primaryButtonClass} w-full`} onClick={() => toggle(selected)}><Workflow className="size-3.5" />Authorize {selected.name}</button>}</div> : null}</Modal>
  </div>;
}

export default IntegrationsPage;
