import { Activity, AlertTriangle, ArchiveRestore, ArrowRight, CheckCircle2, CloudUpload, FolderTree, Plus, Rocket, Server as ServerIcon, ShieldCheck, Terminal, Users, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { WorkspaceDataStatus } from "@/components/workspace-data-status";
import { PageHeader } from "@/components/page-header";
import { Avatar, Badge, Button, Progress, StatusBadge } from "@/components/ui";
import { useAuth } from "@/contexts/auth-context";
import { api } from "@/lib/api";
import { activities, backups, deployments, metrics, notifications, servers, transfers } from "@/lib/mock-data";
import { useLiveResource } from "@/lib/use-live-resource";
import { cn, formatBytes, relativeTime } from "@/lib/utils";
import type { ActivityEvent, Deployment, Notification, Server } from "@/types";

type OverviewCounts = { workspaces: number; servers: number; members: number; backups: number; automations: number; openAlerts: number };
type TransferSummary = { total: number; completed: number; failed: number; bytesTransferred: number };
type OverviewServer = Server & { workspaceId?: string; hasMetrics?: boolean };
type OverviewData = { organizationName: string; counts: OverviewCounts; transfers: TransferSummary; servers: OverviewServer[]; recentActivity: ActivityEvent[]; recentDeployments: Deployment[]; alerts: Notification[]; chart: Array<{ time: string; average: number }> };
type BackendOverview = { organization: { name: string }; counts: Record<keyof OverviewCounts, number | string>; transfers: { total: number | string; completed: number | string; failed: number | string; bytesTransferred: number | string }; recentActivity: Array<{ id: string; action: string; resourceType: string; resourceId?: string; createdAt: string; actor?: string }>; recentDeployments: Array<{ id: string; name: string; environment: string; version: string; status: string; createdAt: string }> };
type BackendServer = { id: string; workspaceId: string; workspaceName?: string; name: string; host: string; port: number; username: string; rootPath: string; environment: Server["environment"]; adapterMode: string; status: string; lastCheckedAt?: string; lastLatencyMs?: number | string };
type BackendMonitoring = { servers: Array<{ serverId: string; status?: string; cpuPercent?: number | string; memoryPercent?: number | string; diskPercent?: number | string; latencyMs?: number | string; sampledAt?: string }>; alerts: Array<{ id: string; title: string; message: string; severity: string; status: string; createdAt: string }> };

const previewOverview: OverviewData = {
  organizationName: "Acme Engineering",
  counts: { workspaces: 2, servers: servers.length, members: 5, backups: backups.filter((item) => item.status === "complete").length, automations: 3, openAlerts: notifications.filter((item) => item.type === "critical" && !item.read).length },
  transfers: { total: transfers.length, completed: transfers.filter((item) => item.status === "complete").length, failed: transfers.filter((item) => item.status === "failed").length, bytesTransferred: transfers.filter((item) => item.status === "complete").reduce((sum, item) => sum + item.bytes, 0) },
  servers: servers.map((server) => ({ ...server, hasMetrics: true })),
  recentActivity: activities,
  recentDeployments: deployments,
  alerts: notifications,
  chart: metrics.map((item) => ({ time: item.time, average: Math.round((item.cpu + item.memory) / 2) })),
};
const emptyOverview: OverviewData = { organizationName: "Workspace", counts: { workspaces: 0, servers: 0, members: 0, backups: 0, automations: 0, openAlerts: 0 }, transfers: { total: 0, completed: 0, failed: 0, bytesTransferred: 0 }, servers: [], recentActivity: [], recentDeployments: [], alerts: [], chart: [] };
function initials(name: string) { return name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "SY"; }
function titleCase(value: string) { return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value; }

async function loadOverview(): Promise<OverviewData> {
  const [overview, serverRows, monitoring] = await Promise.all([api.get<BackendOverview>("/overview"), api.get<BackendServer[]>("/servers?limit=12"), api.get<BackendMonitoring>("/monitoring")]);
  const samples = new Map(monitoring.servers.map((sample) => [sample.serverId, sample]));
  const mappedServers: OverviewServer[] = serverRows.map((server) => {
    const sample = samples.get(server.id);
    return { id: server.id, workspaceId: server.workspaceId, name: server.name, environment: server.environment, status: (["online", "degraded", "offline", "maintenance"].includes(server.status) ? server.status : sample?.status === "healthy" ? "online" : sample?.status === "critical" ? "degraded" : "offline") as Server["status"], host: server.host, port: server.port, protocol: "SFTP", username: server.username, region: server.workspaceName ?? "Workspace", provider: titleCase(server.adapterMode), rootPath: server.rootPath, latency: Number(sample?.latencyMs ?? server.lastLatencyMs ?? 0), cpu: Number(sample?.cpuPercent ?? 0), memory: Number(sample?.memoryPercent ?? 0), disk: Number(sample?.diskPercent ?? 0), uptime: "—", lastSeen: sample?.sampledAt ?? server.lastCheckedAt ?? new Date(0).toISOString(), tags: [server.environment], hasMetrics: Boolean(sample?.sampledAt) };
  });
  const counts = Object.fromEntries(Object.entries(overview.counts).map(([key, value]) => [key, Number(value)])) as unknown as OverviewCounts;
  const transferSummary: TransferSummary = { total: Number(overview.transfers.total), completed: Number(overview.transfers.completed), failed: Number(overview.transfers.failed), bytesTransferred: Number(overview.transfers.bytesTransferred) };
  const recentActivity = overview.recentActivity.map((item): ActivityEvent => ({ id: item.id, actor: item.actor ?? "System actor", initials: initials(item.actor ?? "System actor"), action: item.action, resource: item.resourceId ?? item.resourceType, resourceType: item.resourceType, severity: item.action.startsWith("delete") ? "warning" : item.action.startsWith("post") ? "success" : "info", createdAt: item.createdAt }));
  const recentDeployments = overview.recentDeployments.map((item): Deployment => ({ id: item.id, project: item.name, environment: titleCase(item.environment), branch: "managed", commit: item.version, author: "Orbit operator", status: item.status === "succeeded" || item.status === "rolled_back" ? "ready" : item.status === "running" ? "building" : item.status === "failed" ? "failed" : "cancelled", duration: "Recorded", createdAt: item.createdAt }));
  const openAlerts = monitoring.alerts.filter((item) => item.status !== "resolved").map((item): Notification => ({ id: item.id, title: item.title, body: item.message, type: (["info", "success", "warning", "critical"].includes(item.severity) ? item.severity : "warning") as Notification["type"], read: item.status !== "open", createdAt: item.createdAt }));
  const chart = mappedServers.filter((server) => server.hasMetrics).map((server) => ({ time: server.name, average: Math.round((server.cpu + server.memory) / 2) }));
  return { organizationName: overview.organization.name, counts, transfers: transferSummary, servers: mappedServers, recentActivity, recentDeployments, alerts: openAlerts, chart };
}

export function OverviewPage() {
  const { user } = useAuth();
  const resource = useLiveResource(previewOverview, emptyOverview, loadOverview);
  const { data, live } = resource;
  const healthy = data.servers.filter((server) => server.status === "online").length;
  const activeAlert = data.alerts.find((notification) => notification.type === "critical" && !notification.read) ?? data.alerts.find((notification) => !notification.read);
  const firstServer = data.servers[0];
  const quickActions = [
    { title: "Connect server", detail: "SFTP, pinned host key, or demo adapter", icon: Plus, to: "/workspace/servers?new=true" },
    { title: "Explore files", detail: firstServer ? `Browse ${firstServer.name}` : "Choose a connected server", icon: FolderTree, to: firstServer ? `/workspace/servers/${firstServer.id}/files` : "/workspace/servers" },
    { title: "Open terminal", detail: "Start an audited session", icon: Terminal, to: "/workspace/terminal" },
    { title: "Create backup", detail: "Create a recovery point", icon: ArchiveRestore, to: "/workspace/backups?new=true" },
  ];
  const completionRate = data.transfers.total ? Math.round(data.transfers.completed / data.transfers.total * 100) : 0;
  const pulse = [
    { icon: CloudUpload, title: `${data.transfers.total} transfers in 30 days`, detail: `${formatBytes(data.transfers.bytesTransferred)} completed · ${data.transfers.failed} failed`, tone: "text-blue-300", progress: completionRate },
    { icon: ArchiveRestore, title: `${data.counts.backups} recovery points`, detail: "Completed backup catalog", tone: "text-violet-300", progress: data.counts.backups ? 100 : 0 },
    { icon: Rocket, title: data.recentDeployments[0]?.project ?? "No deployments yet", detail: data.recentDeployments[0] ? `${data.recentDeployments[0].environment} · ${data.recentDeployments[0].status}` : "Create the first release", tone: "text-amber-300", progress: data.recentDeployments[0]?.status === "ready" ? 100 : data.recentDeployments[0]?.status === "building" ? 55 : 0 },
  ];

  return <>
    <PageHeader title={`Good evening, ${user?.name?.split(" ")[0] ?? "developer"}`} subtitle={`${data.organizationName} · ${user?.plan ?? "Workspace"} workspace`} actions={<><Link to="/workspace/activity"><Button variant="outline"><Activity />Live activity</Button></Link><Link to="/workspace/servers?new=true"><Button><Plus />Connect server</Button></Link></>} />
    <div className="mx-auto max-w-[1500px] space-y-8 px-4 py-5 sm:px-6 md:px-8 md:py-7">
      <WorkspaceDataStatus live={live} loading={resource.loading} error={resource.error} onRetry={() => void resource.refresh().catch(() => undefined)} />
      {activeAlert ? <div className="flex flex-col gap-3 rounded-lg border border-amber-400/20 bg-amber-400/[0.055] px-4 py-3 sm:flex-row sm:items-center"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-amber-400/10 text-amber-300"><AlertTriangle className="size-3.5" /></span><div className="min-w-0 flex-1"><p className="text-[10px] font-medium text-amber-200">{activeAlert.title}</p><p className="mt-0.5 truncate text-[9px] text-amber-200/55">{activeAlert.body}</p></div><Link to="/workspace/monitoring" className="flex items-center gap-1 text-[9px] text-amber-200 hover:text-white">Investigate<ArrowRight className="size-3" /></Link></div> : null}
      <section aria-label="Quick actions" className="grid border-y border-border sm:grid-cols-2 xl:grid-cols-4">{quickActions.map((item, index) => <Link key={item.title} to={item.to} className={cn("group flex items-center gap-3 px-3 py-3.5 hover:bg-muted/40", index % 2 === 0 && "sm:border-r", index < 2 && "border-b xl:border-b-0", index < 3 && "xl:border-r")}><span className="grid size-9 shrink-0 place-items-center rounded-md bg-muted text-muted-foreground"><item.icon className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{item.title}</strong><span className="mt-0.5 block truncate text-[9px] text-muted-foreground">{item.detail}</span></span><ArrowRight className="size-3.5 text-zinc-600 transition-transform group-hover:translate-x-0.5 group-hover:text-zinc-300" /></Link>)}</section>
      <section aria-label="Workspace metrics" className="grid grid-cols-2 border-y border-border lg:grid-cols-6">{[
        { label: "Servers online", value: `${healthy}/${data.counts.servers}`, icon: ServerIcon, detail: `${data.counts.workspaces} workspaces` },
        { label: "Open alerts", value: data.counts.openAlerts, icon: AlertTriangle, detail: "Monitoring state" },
        { label: "30d transfers", value: data.transfers.total, icon: CloudUpload, detail: formatBytes(data.transfers.bytesTransferred) },
        { label: "Backups", value: data.counts.backups, icon: ArchiveRestore, detail: "Recovery-ready" },
        { label: "Automations", value: data.counts.automations, icon: Zap, detail: "Enabled workflows" },
        { label: "Team members", value: data.counts.members, icon: Users, detail: "Active access" },
      ].map((item, index) => <div key={item.label} className={cn("flex min-w-0 items-center gap-3 p-3.5", index % 2 === 0 && "border-r", index < 4 && "border-b lg:border-b-0", index < 5 && "lg:border-r")}><span className="grid size-8 shrink-0 place-items-center rounded-md bg-muted text-muted-foreground"><item.icon className="size-3.5" /></span><span className="min-w-0"><strong className="block text-lg tabular-nums">{item.value}</strong><span className="block truncate text-[8px] text-muted-foreground">{item.label} · {item.detail}</span></span></div>)}</section>
      <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-semibold">Your servers</h2><p className="mt-1 text-[10px] text-muted-foreground">Connection health and latest recorded resource pressure</p></div><Link to="/workspace/servers" className="text-[9px] text-muted-foreground hover:text-foreground">View all</Link></div>{data.servers.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.servers.slice(0, 3).map((server) => <Link key={server.id} to={`/workspace/servers/${server.id}`} className="group rounded-lg border border-border bg-card p-4 transition-colors hover:border-white/20"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-muted text-muted-foreground"><ServerIcon className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="truncate text-xs font-medium">{server.name}</h3><StatusBadge status={server.status} /></div><p className="mt-1 truncate font-mono text-[8px] text-zinc-600">{server.username}@{server.host}:{server.port}</p></div></div><div className="mt-5 grid grid-cols-3 gap-4">{[["CPU", server.cpu], ["RAM", server.memory], ["Disk", server.disk]].map(([label, value]) => <div key={label}><div className="mb-1.5 flex justify-between text-[8px] text-muted-foreground"><span>{label}</span><span>{server.hasMetrics ? `${value}%` : "—"}</span></div><Progress value={server.hasMetrics ? Number(value) : 0} className="h-px" indicatorClassName={Number(value) > 75 ? "bg-amber-400" : "bg-zinc-400"} /></div>)}</div><div className="mt-4 flex items-center justify-between border-t border-border pt-3 text-[8px] text-zinc-600"><span>{server.region}</span><span className="font-mono">{server.latency ? `${server.latency} ms` : "not sampled"}</span></div></Link>)}</div> : <div className="rounded-lg border border-dashed border-border p-8 text-center text-xs text-muted-foreground">No servers connected yet.</div>}</section>
      <section className="grid gap-8 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,.7fr)]"><div><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-semibold">{live ? "Latest fleet load" : "Fleet load"}</h2><p className="mt-1 text-[10px] text-muted-foreground">{live ? "Latest CPU and memory sample by server" : "Aggregate CPU and memory · last 24 hours"}</p></div>{data.chart.length ? <Badge tone="success" dot>Recorded</Badge> : null}</div><div className="h-64 rounded-lg border border-border bg-card p-4">{data.chart.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.chart} margin={{ top: 8, right: 2, left: 2, bottom: 0 }}><defs><linearGradient id="overviewCpu" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6b82ff" stopOpacity={0.28} /><stop offset="100%" stopColor="#6b82ff" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="time" tick={{ fill: "#52525b", fontSize: 8 }} axisLine={false} tickLine={false} interval={live ? 0 : 3} /><Tooltip contentStyle={{ background: "#171717", border: "1px solid rgba(255,255,255,.1)", borderRadius: 8, fontSize: 9 }} /><Area isAnimationActive={false} dot={live} type="monotone" dataKey="average" stroke="#7c8cff" strokeWidth={1.5} fill="url(#overviewCpu)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-xs text-zinc-600">Run a monitoring probe to record fleet load.</div>}</div></div><aside><div className="mb-3"><h2 className="text-sm font-semibold">Operations pulse</h2><p className="mt-1 text-[10px] text-muted-foreground">Current workspace records</p></div><div className="divide-y divide-border border-y border-border">{pulse.map((item) => <div key={item.title} className="flex gap-3 py-3"><span className={cn("grid size-8 shrink-0 place-items-center rounded-md bg-muted", item.tone)}><item.icon className="size-3.5" /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-[10px] font-medium">{item.title}</p><span className="text-[8px] text-muted-foreground">{item.progress}%</span></div><Progress value={item.progress} className="mt-2 h-1" indicatorClassName="bg-zinc-300" /><p className="mt-1.5 text-[8px] text-muted-foreground">{item.detail}</p></div></div>)}</div></aside></section>
      <section className="grid gap-8 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-semibold">Recent activity</h2><p className="mt-1 text-[10px] text-muted-foreground">Audited workspace mutations</p></div><Link to="/workspace/activity" className="text-[9px] text-muted-foreground hover:text-foreground">Full audit</Link></div><div className="divide-y divide-border border-y border-border">{data.recentActivity.length ? data.recentActivity.slice(0, 5).map((event) => <article key={event.id} className="flex items-center gap-3 py-3"><Avatar name={event.actor} className="size-7" /><div className="min-w-0 flex-1"><p className="truncate text-[10px]"><span className="font-medium">{event.actor}</span> <span className="text-muted-foreground">{event.action}</span> <span>{event.resource}</span></p><p className="mt-0.5 truncate text-[8px] text-muted-foreground">{event.resourceType} · {relativeTime(event.createdAt)}</p></div><Badge tone={event.severity === "critical" ? "danger" : event.severity === "warning" ? "warning" : event.severity === "success" ? "success" : "neutral"}>{event.resourceType}</Badge></article>) : <div className="py-8 text-center text-xs text-zinc-600">No audited mutations yet.</div>}</div></div><aside><div className="mb-3"><h2 className="text-sm font-semibold">Workspace controls</h2><p className="mt-1 text-[10px] text-muted-foreground">Current recovery and access coverage</p></div><div className="rounded-lg border border-border bg-card p-4"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-full border-4 border-indigo-400/70 text-lg font-semibold text-indigo-300">{data.counts.openAlerts}</span><div><p className="text-xs font-medium">Open alerts</p><p className="mt-1 text-[9px] text-muted-foreground">{data.counts.openAlerts ? "Review monitoring events" : "No open alerts"}</p></div></div><div className="mt-5 space-y-2.5 border-t border-border pt-4">{[{ label: "Connected servers", value: data.counts.servers }, { label: "Active members", value: data.counts.members }, { label: "Recovery points", value: data.counts.backups }, { label: "Enabled automations", value: data.counts.automations }].map((item) => <div key={item.label} className="flex items-center gap-2 text-[9px]"><span className={cn("size-1.5 rounded-full", item.value ? "bg-emerald-400" : "bg-zinc-600")} /><span className="flex-1 text-muted-foreground">{item.label}</span><span>{item.value}</span></div>)}</div><Link to="/workspace/settings/security" className="mt-5 flex h-8 items-center justify-center gap-2 rounded-md border border-border text-[9px] text-muted-foreground hover:bg-muted hover:text-foreground"><ShieldCheck className="size-3.5" />Open security center</Link></div></aside></section>
    </div>
  </>;
}

export default OverviewPage;
