import { FormEvent, useState } from "react";
import { Camera, Globe2, Mail, Save, User, UserCircle2 } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/contexts/auth-context";
import { buttonClass, controlClass, Field, PageHeader, Panel, primaryButtonClass, Toggle } from "./_shared";

export function ProfileSettingsPage() {
  const { user } = useAuth();
  const [form, setForm] = useState({ name: (user?.name ?? ""), email: (user?.email ?? ""), title: "Platform engineer", timezone: "Asia/Shanghai", language: "English", dateFormat: "MMM d, yyyy" });
  const [prefs, setPrefs] = useState({ compact: true, relative: true, sounds: false });
  function submit(event: FormEvent) { event.preventDefault(); if (!form.name.trim() || !/^\S+@\S+\.\S+$/.test(form.email)) return toast.error("Complete your name and email"); toast.success("Profile settings saved"); }
  return <form onSubmit={submit} className="space-y-5"><PageHeader eyebrow="Personal settings" title="Profile" description="Your identity, locale, and interface preferences across every Orbit workspace." actions={<button type="submit" className={primaryButtonClass}><Save className="size-3.5" />Save profile</button>} />
    <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)]"><Panel title="Profile picture" description="Visible to workspace collaborators"><div className="grid place-items-center py-4 text-center"><span className="grid size-24 place-items-center rounded-full border border-white/[0.09] bg-gradient-to-br from-indigo-500/25 to-violet-500/10 text-2xl font-semibold text-white">AK</span><p className="mt-4 text-sm font-medium text-zinc-200">{form.name}</p><p className="mt-1 text-xs text-zinc-600">Owner · {(user?.organizationName ?? "")}</p><div className="mt-4 flex gap-2"><label className={buttonClass}><Camera className="size-3.5" />Upload<input type="file" accept="image/*" className="hidden" onChange={() => toast.success("New avatar selected")} /></label><button type="button" className={buttonClass} onClick={() => toast.success("Avatar removed")}>Remove</button></div><p className="mt-3 text-[10px] text-zinc-600">PNG, JPG, or WebP · max 5 MB</p></div></Panel><Panel title="Personal information" description="Used for activity records and notifications"><div className="grid gap-4 sm:grid-cols-2"><Field label="Display name"><div className="relative"><User className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-zinc-600" /><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={`${controlClass} w-full pl-9`} /></div></Field><Field label="Job title"><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={`${controlClass} w-full`} /></Field><Field label="Email address" hint="Changing email requires verification."><div className="relative"><Mail className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-zinc-600" /><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className={`${controlClass} w-full pl-9`} /></div></Field><Field label="Account ID"><input readOnly value={(user?.id ?? "")} className={`${controlClass} w-full font-mono opacity-60`} /></Field></div></Panel></div>
    <div className="grid gap-4 lg:grid-cols-2"><Panel title="Locale & formats" description="Dates and times remain stored in UTC"><div className="grid gap-4 sm:grid-cols-2"><Field label="Timezone"><select value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} className={`${controlClass} w-full`}><option>Asia/Shanghai</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select></Field><Field label="Language"><select value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })} className={`${controlClass} w-full`}><option>English</option><option>Chinese</option><option>Spanish</option><option>German</option></select></Field><Field label="Date format"><select value={form.dateFormat} onChange={(e) => setForm({ ...form, dateFormat: e.target.value })} className={`${controlClass} w-full`}><option>MMM d, yyyy</option><option>dd/MM/yyyy</option><option>yyyy-MM-dd</option></select></Field><div className="flex items-end"><div className="flex h-9 w-full items-center gap-2 rounded-lg border border-white/[0.07] px-3 text-xs text-zinc-500"><Globe2 className="size-3.5" />Preview · Jul 19, 2026</div></div></div></Panel><Panel title="Interface preferences" description="Applied on this account"><div className="divide-y divide-white/[0.06]">{[{ key: "compact", title: "Compact data tables", description: "Show more server data per screen" }, { key: "relative", title: "Relative timestamps", description: "Show “8 minutes ago” where possible" }, { key: "sounds", title: "Terminal sounds", description: "Audible cue when a long command completes" }].map((item) => <div key={item.key} className="flex items-center justify-between gap-3 py-3"><div><p className="text-xs font-medium text-zinc-300">{item.title}</p><p className="mt-1 text-[10px] text-zinc-600">{item.description}</p></div><Toggle label={item.title} checked={prefs[item.key as keyof typeof prefs]} onChange={(checked) => setPrefs((x) => ({ ...x, [item.key]: checked }))} /></div>)}</div></Panel></div>
  </form>;
}

export const ProfilePage = ProfileSettingsPage;
export default ProfileSettingsPage;
