import { useMemo, useState } from "react";
import { BookOpenCheck, CheckCircle2, Clock3, Code2, Copy, Database, Play, Plus, SearchX, ServerCog, ShieldCheck, Star, Terminal } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { buttonClass, controlClass, EmptyState, IconButton, Modal, PageHeader, Panel, primaryButtonClass, SearchField, Stat, StatusBadge } from "./_shared";

type Runbook = { id: string; name: string; description: string; category: string; command: string; steps: number; duration: string; lastRun: string; runs: number; favorite: boolean; risk: "low" | "medium" | "high" };
const seed: Runbook[] = [
  { id: "r1", name: "Restart application service", description: "Gracefully drain, restart, and verify the API service health.", category: "Operations", command: "sudo systemctl restart acme-api", steps: 4, duration: "~2 min", lastRun: "18 minutes ago", runs: 94, favorite: true, risk: "medium" },
  { id: "r2", name: "Rotate application logs", description: "Archive current logs and safely reclaim disk capacity.", category: "Maintenance", command: "sudo logrotate -f /etc/logrotate.d/acme", steps: 3, duration: "~45 sec", lastRun: "4 days ago", runs: 31, favorite: false, risk: "low" },
  { id: "r3", name: "Database health check", description: "Inspect connections, replica lag, locks, and slow queries.", category: "Database", command: "./ops/db-health.sh --report", steps: 6, duration: "~3 min", lastRun: "1 hour ago", runs: 226, favorite: true, risk: "low" },
  { id: "r4", name: "Rollback latest release", description: "Restore the prior artifact and verify all production checks.", category: "Deployment", command: "orbit rollback --previous --verify", steps: 7, duration: "~5 min", lastRun: "12 days ago", runs: 8, favorite: true, risk: "high" },
];

export function RunbooksPage() {
  const [items, setItems] = useState(seed);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState<Runbook>();
  const [draft, setDraft] = useState({ name: "", description: "", command: "", category: "Operations" });
  const filtered = useMemo(() => items.filter((x) => (category === "all" || x.category === category) && `${x.name} ${x.description} ${x.command}`.toLowerCase().includes(query.toLowerCase())), [items, query, category]);

  function create() { if (!draft.name.trim() || !draft.command.trim()) return toast.error("Name and command are required"); setItems((x) => [{ id: `r_${Date.now()}`, ...draft, steps: 1, duration: "~1 min", lastRun: "Never", runs: 0, favorite: false, risk: "medium" }, ...x]); setOpen(false); toast.success("Runbook saved"); }

  return <div className="space-y-5">
    <PageHeader eyebrow="Repeatable operations" title="Runbooks" description="Package trusted commands into reviewed, auditable procedures anyone on-call can run safely." actions={<button className={primaryButtonClass} onClick={() => setOpen(true)}><Plus className="size-3.5" />New runbook</button>} />
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Published runbooks" value={items.length} detail="3 reviewed this month" icon={BookOpenCheck} /><Stat label="Runs this month" value="128" detail="100% audit coverage" icon={Terminal} tone="emerald" /><Stat label="Operator time saved" value="8.6h" detail="Compared with manual steps" icon={Clock3} tone="sky" /></div>
    <Panel title="Runbook library" description="Reviewed procedures available to workspace operators" flush><div className="grid gap-2 border-b border-white/[0.06] p-3 sm:grid-cols-[minmax(0,1fr)_180px]"><SearchField value={query} onChange={setQuery} placeholder="Search runbooks and commands" /><select value={category} onChange={(e) => setCategory(e.target.value)} className={controlClass}><option value="all">All categories</option><option>Operations</option><option>Maintenance</option><option>Database</option><option>Deployment</option></select></div>{filtered.length ? <div className="grid gap-3 p-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className="flex min-h-64 flex-col rounded-xl border border-white/[0.07] bg-black/10 p-4 transition hover:-translate-y-0.5 hover:border-white/[0.13]"><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-lg bg-white/[0.04] text-zinc-400">{item.category === "Database" ? <Database className="size-4" /> : item.category === "Deployment" ? <ServerCog className="size-4" /> : <Code2 className="size-4" />}</span><IconButton title="Favorite" onClick={() => setItems((rows) => rows.map((x) => x.id === item.id ? { ...x, favorite: !x.favorite } : x))}><Star className={cn("size-4", item.favorite && "fill-amber-400 text-amber-400")} /></IconButton></div><div className="mt-4 flex items-center gap-2"><h3 className="text-sm font-semibold text-zinc-100">{item.name}</h3><StatusBadge status={item.risk === "high" ? "critical" : item.risk === "medium" ? "warning" : "success"} /></div><p className="mt-1 flex-1 text-xs leading-5 text-zinc-500">{item.description}</p><code className="mt-4 block truncate rounded-lg border border-white/[0.06] bg-black/30 px-3 py-2 text-[10px] text-zinc-400">$ {item.command}</code><div className="mt-3 flex items-center justify-between text-[10px] text-zinc-600"><span>{item.steps} steps · {item.duration}</span><span>{item.runs} runs</span></div><div className="mt-4 flex gap-2"><button className={`${buttonClass} flex-1`} onClick={() => setSelected(item)}>Preview</button><button className={`${primaryButtonClass} flex-1`} onClick={() => { toast.success(`${item.name} started with approval record`); setItems((rows) => rows.map((x) => x.id === item.id ? { ...x, runs: x.runs + 1, lastRun: "Just now" } : x)); }}><Play className="size-3" />Run</button></div></article>)}</div> : <EmptyState icon={SearchX} title="No runbooks found" description="Try another category or create a procedure for your team." />}</Panel>
    <Panel title="Recent executions" description="Latest audited procedure runs" flush><div className="divide-y divide-white/[0.06]">{items.slice(0, 3).map((item, i) => <div key={item.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_160px_120px_auto] sm:items-center"><div><p className="text-xs font-medium text-zinc-300">{item.name}</p><p className="mt-1 text-[10px] text-zinc-600">Run by {i ? "Sara Malik" : "Adeel Khan"}</p></div><span className="text-[10px] text-zinc-500">{item.lastRun}</span><StatusBadge status="complete" /><span className="text-right font-mono text-[10px] text-zinc-600">run_{item.id}_0{i + 1}</span></div>)}</div></Panel>
    <Modal open={open} onClose={() => setOpen(false)} title="Create runbook" description="Start with one command; approval and verification steps can be added later." footer={<><button className={buttonClass} onClick={() => setOpen(false)}>Cancel</button><button className={primaryButtonClass} onClick={create}><CheckCircle2 className="size-3.5" />Save runbook</button></>} wide><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-zinc-400 sm:col-span-2">Name<input className={`${controlClass} mt-1.5 w-full`} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label className="text-xs text-zinc-400">Category<select className={`${controlClass} mt-1.5 w-full`} value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })}><option>Operations</option><option>Maintenance</option><option>Database</option><option>Deployment</option></select></label><label className="text-xs text-zinc-400">Description<input className={`${controlClass} mt-1.5 w-full`} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /></label><label className="text-xs text-zinc-400 sm:col-span-2">Command<textarea className={`${controlClass} mt-1.5 min-h-24 w-full py-2 font-mono`} value={draft.command} onChange={(e) => setDraft({ ...draft, command: e.target.value })} placeholder="sudo systemctl status acme-api" /></label></div></Modal>
    <Modal open={Boolean(selected)} onClose={() => setSelected(undefined)} title={selected?.name ?? "Runbook preview"} description="Review every command before starting this procedure.">{selected ? <div className="space-y-4"><div className="rounded-lg border border-white/[0.07] bg-black/20 p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-zinc-600">Step 1 of {selected.steps}</span><button onClick={() => { navigator.clipboard.writeText(selected.command); toast.success("Command copied"); }} className={buttonClass}><Copy className="size-3" />Copy</button></div><code className="mt-3 block whitespace-pre-wrap text-xs leading-6 text-emerald-300">{selected.command}</code></div><p className="text-xs leading-5 text-zinc-500">This run creates a signed audit record. High-risk procedures require an approver before execution.</p><button className={`${primaryButtonClass} w-full`} onClick={() => { toast.success("Runbook execution started"); setSelected(undefined); }}><ShieldCheck className="size-3.5" />Start audited run</button></div> : null}</Modal>
  </div>;
}

export default RunbooksPage;
