import { FormEvent, useState } from "react";
import { Check, Copy, KeyRound, Laptop, LockKeyhole, Plus, ShieldCheck, Smartphone, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { buttonClass, controlClass, IconButton, Modal, PageHeader, Panel, primaryButtonClass, StatusBadge, Toggle } from "./_shared";

export function SecuritySettingsPage() {
  const [mfa, setMfa] = useState(true); const [modal, setModal] = useState<"mfa" | "recovery" | "ssh" | null>(null);
  const [sessions, setSessions] = useState([{ id: "s1", device: "Chrome on Windows", location: "Shanghai, CN", ip: "103.21.244.8", current: true, seen: "Active now" }, { id: "s2", device: "Safari on iPhone", location: "Shanghai, CN", ip: "103.21.244.8", current: false, seen: "3 hours ago" }, { id: "s3", device: "Chrome on macOS", location: "Singapore, SG", ip: "87.244.12.3", current: false, seen: "5 days ago" }]);
  const [keys, setKeys] = useState([{ id: "k1", name: "Adeel · MacBook", fingerprint: "SHA256:Nxz4Qb1m…dK82", added: "May 4, 2026" }, { id: "k2", name: "Office workstation", fingerprint: "SHA256:8Pf2Mda7…vZ19", added: "Feb 18, 2026" }]);
  function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (String(data.get("new")).length < 12) return toast.error("Use at least 12 characters"); if (data.get("new") !== data.get("confirm")) return toast.error("Passwords do not match"); event.currentTarget.reset(); toast.success("Password changed; other sessions were revoked"); }
  return <div className="space-y-5"><PageHeader eyebrow="Account protection" title="Security" description="Protect your account with strong authentication, trusted SSH keys, and session controls." actions={<span className="inline-flex items-center gap-2 text-xs text-emerald-300"><ShieldCheck className="size-4" />Security score 92 / 100</span>} />
    <div className="grid gap-4 lg:grid-cols-2"><Panel title="Multi-factor authentication" description="Require a second factor at sign-in"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-300"><Smartphone className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-medium text-zinc-200">Authenticator app</p><StatusBadge status={mfa ? "active" : "disabled"} /></div><p className="mt-1 text-xs leading-5 text-zinc-500">Use a time-based one-time password from your authenticator app.</p><div className="mt-4 flex flex-wrap gap-2"><button className={buttonClass} onClick={() => setModal(mfa ? "recovery" : "mfa")}>{mfa ? "View recovery codes" : "Set up MFA"}</button><Toggle checked={mfa} onChange={(checked) => { setMfa(checked); toast.success(checked ? "MFA enabled" : "MFA disabled"); }} label="MFA" /></div></div></div></Panel><Panel title="Change password" description="Last changed 94 days ago"><form onSubmit={password} className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] text-zinc-400 sm:col-span-2">Current password<input name="current" type="password" required className={`${controlClass} mt-1.5 w-full`} /></label><label className="text-[10px] text-zinc-400">New password<input name="new" type="password" required className={`${controlClass} mt-1.5 w-full`} /></label><label className="text-[10px] text-zinc-400">Confirm password<input name="confirm" type="password" required className={`${controlClass} mt-1.5 w-full`} /></label><button className={`${buttonClass} sm:col-span-2`}>Update password</button></form></Panel></div>
    <Panel title="Active sessions" description="Browsers and devices signed into this account" actions={<button className={buttonClass} onClick={() => { setSessions((x) => x.filter((s) => s.current)); toast.success("Other sessions revoked"); }}>Revoke others</button>} flush><div className="divide-y divide-white/[0.06]">{sessions.map((session) => <div key={session.id} className="grid gap-3 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_170px_120px_auto] sm:items-center"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-white/[0.04] text-zinc-500"><Laptop className="size-3.5" /></span><div><div className="flex items-center gap-2"><p className="text-xs font-medium text-zinc-300">{session.device}</p>{session.current ? <StatusBadge status="current" /> : null}</div><p className="mt-1 text-[10px] text-zinc-600">{session.location}</p></div></div><span className="font-mono text-[10px] text-zinc-500">{session.ip}</span><span className="text-[10px] text-zinc-500">{session.seen}</span>{!session.current ? <IconButton title="Revoke session" onClick={() => { setSessions((x) => x.filter((s) => s.id !== session.id)); toast.success("Session revoked"); }}><Trash2 className="size-3.5" /></IconButton> : <span />}</div>)}</div></Panel>
    <Panel title="SSH public keys" description="Keys authorized for browser terminal and agent connections" actions={<button className={primaryButtonClass} onClick={() => setModal("ssh")}><Plus className="size-3" />Add key</button>} flush><div className="divide-y divide-white/[0.06]">{keys.map((key) => <div key={key.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_220px_120px_auto] sm:items-center"><div className="flex items-center gap-2"><KeyRound className="size-4 text-indigo-300" /><span className="text-xs font-medium text-zinc-300">{key.name}</span></div><code className="text-[10px] text-zinc-500">{key.fingerprint}</code><span className="text-[10px] text-zinc-600">Added {key.added}</span><IconButton title="Delete key" onClick={() => { setKeys((x) => x.filter((k) => k.id !== key.id)); toast.success("SSH key removed"); }}><Trash2 className="size-3.5" /></IconButton></div>)}</div></Panel>
    <Modal open={Boolean(modal)} onClose={() => setModal(null)} title={modal === "ssh" ? "Add SSH public key" : modal === "mfa" ? "Set up authenticator" : "Recovery codes"} description={modal === "recovery" ? "Each code can be used once. Store them somewhere safe." : undefined}>{modal === "ssh" ? <div className="space-y-3"><input placeholder="Key name" className={`${controlClass} w-full`} /><textarea placeholder="ssh-ed25519 AAAA…" className={`${controlClass} min-h-28 w-full py-2 font-mono`} /><button className={`${primaryButtonClass} w-full`} onClick={() => { setKeys((x) => [...x, { id: `k_${Date.now()}`, name: "New workstation", fingerprint: "SHA256:pending…verify", added: "Just now" }]); setModal(null); toast.success("SSH key added"); }}>Add and verify key</button></div> : modal === "mfa" ? <div className="text-center"><div className="mx-auto grid size-36 place-items-center bg-white font-mono text-black">QR CODE</div><p className="mt-3 font-mono text-xs text-zinc-400">JBSWY3DPEHPK3PXP</p><button className={`${primaryButtonClass} mt-4`} onClick={() => { setMfa(true); setModal(null); toast.success("Authenticator verified"); }}>Verify code</button></div> : <div><div className="grid grid-cols-2 gap-2 rounded-lg border border-white/[0.07] bg-black/20 p-4 font-mono text-xs text-zinc-300">{["7H2K-A9PM", "8WQ4-X2LT", "3FNM-K6RV", "9DPL-T4QE", "5VJ8-C1SY", "2RQA-M7UX"].map((x) => <span key={x}>{x}</span>)}</div><button className={`${buttonClass} mt-3 w-full`} onClick={() => toast.success("Recovery codes copied")}><Copy className="size-3.5" />Copy all codes</button></div>}</Modal>
  </div>;
}

export const SecurityPage = SecuritySettingsPage;
export default SecuritySettingsPage;
