import { FormEvent, useState } from "react";
import { AlertTriangle, Building2, Check, Copy, Database, Globe2, Save, Shield, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { demoCustomer } from "@/lib/mock-data";
import { buttonClass, controlClass, dangerButtonClass, Field, Modal, PageHeader, Panel, primaryButtonClass, Toggle } from "./_shared";

export function WorkspaceSettingsPage() {
  const [form, setForm] = useState({ name: demoCustomer.organizationName, slug: "acme-engineering", timezone: "UTC", defaultEnvironment: "production", root: "/var/www", retention: "365 days" });
  const [policies, setPolicies] = useState({ approvals: true, hostKeys: true, passwordAuth: false, autoLock: true });
  const [dangerOpen, setDangerOpen] = useState(false); const [confirm, setConfirm] = useState("");
  function save(event: FormEvent) { event.preventDefault(); if (!form.name.trim() || !/^[a-z0-9-]+$/.test(form.slug)) return toast.error("Use a valid workspace name and URL slug"); toast.success("Workspace settings saved"); }
  return <form onSubmit={save} className="space-y-5"><PageHeader eyebrow="Organization settings" title="Workspace" description="Configure shared defaults, governance policies, and ownership for Acme Engineering." actions={<button type="submit" className={primaryButtonClass}><Save className="size-3.5" />Save changes</button>} />
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_330px]"><Panel title="Workspace identity" description="Organization-wide profile and URL"><div className="grid gap-4 sm:grid-cols-2"><Field label="Workspace name"><div className="relative"><Building2 className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-zinc-600" /><input className={`${controlClass} w-full pl-9`} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div></Field><Field label="Workspace URL" hint="Changing this updates shared links."><div className="flex"><span className="flex h-9 items-center rounded-l-lg border border-r-0 border-white/[0.08] bg-white/[0.025] px-2 text-[10px] text-zinc-600">orbit.dev/</span><input className={`${controlClass} min-w-0 flex-1 rounded-l-none`} value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value.toLowerCase() })} /></div></Field><Field label="Workspace ID"><div className="flex gap-2"><input readOnly className={`${controlClass} min-w-0 flex-1 font-mono opacity-60`} value={demoCustomer.organizationId} /><button type="button" className={buttonClass} onClick={() => { navigator.clipboard.writeText(demoCustomer.organizationId); toast.success("Workspace ID copied"); }}><Copy className="size-3" /></button></div></Field><Field label="Default timezone"><select className={`${controlClass} w-full`} value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })}><option>UTC</option><option>Asia/Shanghai</option><option>America/New_York</option><option>Europe/London</option></select></Field></div></Panel><Panel title="Ownership" description="Primary workspace authority"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-indigo-500/15 text-sm font-semibold text-indigo-200">AK</span><div><p className="text-sm font-medium text-zinc-200">Adeel Khan</p><p className="text-[10px] text-zinc-600">{demoCustomer.email}</p></div></div><button type="button" className={`${buttonClass} mt-4 w-full`} onClick={() => toast.info("Ownership transfer requires email confirmation")}>Transfer ownership</button><div className="mt-4 border-t border-white/[0.06] pt-4 text-[10px] leading-5 text-zinc-600"><Globe2 className="mr-1 inline size-3" />Created January 8, 2026<br /><Shield className="mr-1 inline size-3" />Data region: United States</div></Panel></div>
    <Panel title="Server defaults" description="Pre-fill new connections; every value can be overridden"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Environment"><select className={`${controlClass} w-full`} value={form.defaultEnvironment} onChange={(e) => setForm({ ...form, defaultEnvironment: e.target.value })}><option value="production">Production</option><option value="staging">Staging</option><option value="development">Development</option></select></Field><Field label="Root path"><input className={`${controlClass} w-full font-mono`} value={form.root} onChange={(e) => setForm({ ...form, root: e.target.value })} /></Field><Field label="Audit retention"><select className={`${controlClass} w-full`} value={form.retention} onChange={(e) => setForm({ ...form, retention: e.target.value })}><option>90 days</option><option>365 days</option><option>7 years</option></select></Field><Field label="Conflict strategy"><select className={`${controlClass} w-full`}><option>Ask before overwrite</option><option>Newest file wins</option><option>Create versioned copy</option></select></Field></div></Panel>
    <Panel title="Workspace policies" description="Security guardrails applied to all members"><div className="grid gap-px overflow-hidden rounded-lg bg-white/[0.06] sm:grid-cols-2">{[{ key: "approvals", title: "Production approvals", desc: "Require an approver for destructive operations" }, { key: "hostKeys", title: "Strict host key checking", desc: "Block changed or unknown SSH fingerprints" }, { key: "passwordAuth", title: "Password authentication", desc: "Allow passwords when SSH keys are unavailable" }, { key: "autoLock", title: "Automatic session lock", desc: "Lock inactive terminals after 15 minutes" }].map((item) => <div key={item.key} className="flex items-center justify-between gap-4 bg-[#101218] p-4"><div><p className="text-xs font-medium text-zinc-300">{item.title}</p><p className="mt-1 text-[10px] leading-4 text-zinc-600">{item.desc}</p></div><Toggle checked={policies[item.key as keyof typeof policies]} onChange={(checked) => setPolicies((x) => ({ ...x, [item.key]: checked }))} label={item.title} /></div>)}</div></Panel>
    <Panel title="Data export & deletion" description="Portable workspace records and irreversible controls"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className="grid size-9 place-items-center rounded-lg bg-sky-500/10 text-sky-300"><Database className="size-4" /></span><div><p className="text-xs font-medium text-zinc-300">Export workspace data</p><p className="mt-1 text-[10px] text-zinc-600">Servers, activity, configurations, and metadata as JSON.</p></div></div><button type="button" className={buttonClass} onClick={() => toast.success("Workspace export is being prepared")}>Request export</button></div><div className="my-5 border-t border-white/[0.06]" /><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className="grid size-9 place-items-center rounded-lg bg-rose-500/10 text-rose-300"><Trash2 className="size-4" /></span><div><p className="text-xs font-medium text-rose-300">Delete workspace</p><p className="mt-1 text-[10px] text-zinc-600">Permanently removes all servers, backups, activity, and member access.</p></div></div><button type="button" className={dangerButtonClass} onClick={() => setDangerOpen(true)}>Delete workspace</button></div></Panel>
    <Modal open={dangerOpen} onClose={() => setDangerOpen(false)} title="Delete Acme Engineering?" description="This action is permanent and cannot be undone." footer={<><button type="button" className={buttonClass} onClick={() => setDangerOpen(false)}>Cancel</button><button type="button" disabled={confirm !== form.slug} className={dangerButtonClass} onClick={() => toast.error("Workspace deletion is disabled in this demo")}>Delete permanently</button></>}><div><div className="flex gap-3 rounded-lg border border-rose-400/20 bg-rose-400/[0.06] p-3 text-xs leading-5 text-rose-200"><AlertTriangle className="mt-0.5 size-4 shrink-0" />All remote sessions will disconnect immediately. Remote server data itself will not be deleted.</div><label className="mt-4 block text-xs text-zinc-400">Type <strong className="font-mono text-zinc-200">{form.slug}</strong> to confirm<input autoFocus value={confirm} onChange={(e) => setConfirm(e.target.value)} className={`${controlClass} mt-1.5 w-full`} /></label></div></Modal>
  </form>;
}

export const WorkspacePage = WorkspaceSettingsPage;
export default WorkspaceSettingsPage;
