import { useMemo, useState } from "react";
import { CalendarClock, Eye, Mail, Megaphone, MessageSquare, MoreHorizontal, MousePointerClick, Pause, Plus, Send, Smartphone, Users } from "lucide-react";
import { toast } from "sonner";
import { relativeTime } from "@/lib/utils";
import { announcements, type Announcement } from "./_data";
import { AdminButton, AdminPageHeader, DetailGrid, Drawer, IconAction, Modal, Pagination, Panel, SearchBox, Stat, StatusPill, usePagination } from "./_shared";

const blank = { title: "", audience: "All customers", channel: "In-app", body: "", status: "draft" as Announcement["status"], publishAt: "" };

export function AnnouncementsAdminPage() {
  const [rows, setRows] = useState(announcements);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [selectedId, setSelectedId] = useState<string>();
  const [editorOpen, setEditorOpen] = useState(false);
  const [draft, setDraft] = useState(blank);
  const selected = rows.find((item) => item.id === selectedId);
  const filtered = useMemo(() => rows.filter((item) => `${item.title} ${item.audience} ${item.author}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || item.status === status)), [query, rows, status]);
  const pagination = usePagination(filtered, 7);
  function saveAnnouncement(publish = false) { if (!draft.title.trim() || !draft.body.trim()) { toast.error("Title and message are required"); return; } const item: Announcement = { id: `ann_${Date.now()}`, title: draft.title, audience: draft.audience, channel: draft.channel, body: draft.body, status: publish ? "published" : draft.publishAt ? "scheduled" : "draft", author: "Maya Chen", publishAt: publish ? new Date().toISOString() : draft.publishAt || "Not scheduled", views: 0, clicks: 0 }; setRows((current) => [item, ...current]); setEditorOpen(false); setDraft(blank); toast.success(publish ? "Announcement published" : item.status === "scheduled" ? "Announcement scheduled" : "Draft saved"); }
  function patch(id: string, values: Partial<Announcement>, message: string) { setRows((current) => current.map((item) => item.id === id ? { ...item, ...values } : item)); toast.success(message); }

  return <>
    <AdminPageHeader title="Announcements" description="Create targeted, multi-channel product messages, maintenance notices, and lifecycle communications." actions={<AdminButton variant="primary" onClick={() => setEditorOpen(true)}><Plus />New announcement</AdminButton>} />
    <div className="adm-stats"><Stat label="Published this month" value={rows.filter((item) => item.status === "published").length} change="+2" detail="vs last month" icon={Megaphone} /><Stat label="Unique views" value={rows.reduce((sum, item) => sum + item.views, 0).toLocaleString()} change="68.4%" detail="audience reach" icon={Eye} /><Stat label="Click-through rate" value={`${(rows.reduce((sum, item) => sum + item.clicks, 0) / Math.max(rows.reduce((sum, item) => sum + item.views, 0), 1) * 100).toFixed(1)}%`} change="+4.2%" detail="across channels" icon={MousePointerClick} /><Stat label="Scheduled" value={rows.filter((item) => item.status === "scheduled").length} change="Next 30m" detail="EU maintenance" icon={CalendarClock} /></div>
    <div className="adm-grid two">
      <div><div className="adm-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search announcements, audience, or author…" /><select className="adm-select" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Any status</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option></select></div><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Announcement</th><th>Status</th><th>Audience</th><th>Channels</th><th>Author</th><th>Views</th><th>Publish time</th><th /></tr></thead><tbody>{pagination.rows.map((item) => <tr className="clickable" key={item.id} onClick={() => setSelectedId(item.id)}><td><div className="adm-primary-cell"><span className="adm-cell-icon"><Megaphone /></span><div className="adm-cell-copy"><b>{item.title}</b><small className="adm-mono">{item.id}</small></div></div></td><td><StatusPill status={item.status} /></td><td>{item.audience}</td><td>{item.channel}</td><td>{item.author}</td><td>{item.views.toLocaleString()}</td><td>{item.publishAt === "Not scheduled" ? "—" : relativeTime(item.publishAt)}</td><td><IconAction label="Open announcement" onClick={(event) => { event.stopPropagation(); setSelectedId(item.id); }}><MoreHorizontal /></IconAction></td></tr>)}</tbody></table><Pagination {...pagination} onPage={pagination.setPage} /></div></div>
      <div className="adm-grid"><Panel title="Channel performance" description="Last 30 days"><div className="adm-check-row"><span className="flex gap-2 items-center"><Smartphone size={13} /><span><b>In-app</b><small>2,184 delivered</small></span></span><span>74.8% viewed</span></div><div className="adm-check-row"><span className="flex gap-2 items-center"><Mail size={13} /><span><b>Email</b><small>1,842 delivered</small></span></span><span>52.1% opened</span></div><div className="adm-check-row"><span className="flex gap-2 items-center"><MessageSquare size={13} /><span><b>Status notices</b><small>811 subscribers</small></span></span><span>98.4% delivered</span></div></Panel><Panel title="Audience health" description="Reachable customer contacts"><div className="adm-kpi-row"><span>In-app eligible</span><span>1,284 users</span></div><div className="adm-kpi-row"><span>Email opted in</span><span>1,119 contacts</span></div><div className="adm-kpi-row"><span>Status subscribers</span><span>811 contacts</span></div><div className="adm-kpi-row"><span>Suppressed</span><span>18 contacts</span></div></Panel><Panel title="Delivery guardrails" description="Applies to every broadcast"><div className="adm-notice"><Users />Large broadcasts are automatically rate-limited and deduplicated across channels. Enterprise maintenance contacts cannot be suppressed.</div></Panel></div>
    </div>

    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(undefined)} title={selected?.title ?? "Announcement"} description={selected?.id} footer={selected && <>{selected.status === "published" ? <AdminButton variant="danger" onClick={() => patch(selected.id, { status: "draft" }, "Announcement unpublished") }><Pause />Unpublish</AdminButton> : <AdminButton variant="primary" onClick={() => patch(selected.id, { status: "published", publishAt: new Date().toISOString() }, "Announcement published") }><Send />Publish now</AdminButton>}</>}>
      {selected && <><div className="flex items-center justify-between mb-4"><StatusPill status={selected.status} /><StatusPill status="info" label={selected.channel} noDot /></div><DetailGrid items={[["Audience", selected.audience], ["Author", selected.author], ["Views", selected.views.toLocaleString()], ["Clicks", selected.clicks.toLocaleString()], ["CTR", selected.views ? `${(selected.clicks / selected.views * 100).toFixed(1)}%` : "—"], ["Publish time", selected.publishAt === "Not scheduled" ? "Not scheduled" : new Date(selected.publishAt).toLocaleString()]]} /><p className="adm-section-label">Customer preview</p><div className="border border-white/10 rounded-lg bg-[#0d1012] p-4"><div className="flex items-center gap-2"><span className="adm-logo-mark" style={{ width: 25, height: 25, transform: "none" }}><span /><span /><span /></span><div><b className="text-[9px]">Orbit update</b><p className="text-[7px] text-zinc-600">{selected.audience}</p></div></div><h3 className="text-sm mt-4">{selected.title}</h3><p className="text-[9px] leading-5 text-zinc-400 mt-2">{selected.body}</p><button className="adm-button primary mt-4">Learn more</button></div><p className="adm-section-label">Delivery activity</p><div className="adm-kpi-row"><span>Messages delivered</span><span>{selected.views ? Math.round(selected.views / .684).toLocaleString() : "—"}</span></div><div className="adm-kpi-row"><span>Unique views</span><span>{selected.views.toLocaleString()}</span></div><div className="adm-kpi-row"><span>Action clicks</span><span>{selected.clicks.toLocaleString()}</span></div></>}
    </Drawer>

    <Modal open={editorOpen} onClose={() => setEditorOpen(false)} title="Compose announcement" description="Preview and target a customer communication before publishing." large footer={<><AdminButton onClick={() => saveAnnouncement(false)}>Save draft</AdminButton><AdminButton variant="primary" onClick={() => saveAnnouncement(true)}><Send />Publish now</AdminButton></>}><div className="adm-form-grid"><div className="adm-field span-2"><label>Announcement title</label><input autoFocus className="adm-input" value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} placeholder="What should customers know?" /></div><div className="adm-field"><label>Audience</label><select className="adm-select w-full" value={draft.audience} onChange={(event) => setDraft((current) => ({ ...current, audience: event.target.value }))}><option>All customers</option><option>Free</option><option>Pro & Enterprise</option><option>Enterprise</option><option>EU organizations</option></select></div><div className="adm-field"><label>Channels</label><select className="adm-select w-full" value={draft.channel} onChange={(event) => setDraft((current) => ({ ...current, channel: event.target.value }))}><option>In-app</option><option>In-app + email</option><option>Status + email</option></select></div><div className="adm-field span-2"><label>Message</label><textarea className="adm-textarea min-h-36" value={draft.body} onChange={(event) => setDraft((current) => ({ ...current, body: event.target.value }))} placeholder="Write a concise, actionable customer message…" /></div><div className="adm-field span-2"><label>Schedule (optional)</label><input className="adm-input" type="datetime-local" value={draft.publishAt} onChange={(event) => setDraft((current) => ({ ...current, publishAt: event.target.value }))} /></div></div>{draft.title && <div className="adm-notice mt-4"><Eye />Preview ready for “{draft.title}” · estimated audience 1,284 users.</div>}</Modal>
  </>;
}

export default AnnouncementsAdminPage;
