import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Headphones, Inbox, LifeBuoy, MessageSquareReply, MoreHorizontal, Plus, Send, Timer, UserCheck } from "lucide-react";
import { toast } from "sonner";
import { relativeTime } from "@/lib/utils";
import { supportTickets, type SupportTicket } from "./_data";
import { AdminButton, AdminPageHeader, Avatar, DetailGrid, Drawer, IconAction, Modal, Pagination, Panel, SearchBox, Stat, StatusPill, usePagination } from "./_shared";

export function SupportAdminPage() {
  const [rows, setRows] = useState(supportTickets);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [priority, setPriority] = useState("all");
  const [selectedId, setSelectedId] = useState<string>();
  const [reply, setReply] = useState("");
  const [newOpen, setNewOpen] = useState(false);
  const selected = rows.find((ticket) => ticket.id === selectedId);
  const filtered = useMemo(() => rows.filter((ticket) => `${ticket.id} ${ticket.subject} ${ticket.customer} ${ticket.assignee}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || ticket.status === status) && (priority === "all" || ticket.priority === priority)), [priority, query, rows, status]);
  const pagination = usePagination(filtered, 7);
  function patch(id: string, values: Partial<SupportTicket>, message?: string) { setRows((current) => current.map((ticket) => ticket.id === id ? { ...ticket, ...values, updatedAt: new Date().toISOString() } : ticket)); if (message) toast.success(message); }
  function sendReply() { if (!selected || !reply.trim()) { toast.error("Write a reply first"); return; } patch(selected.id, { status: "pending", messages: selected.messages + 1 }, "Reply sent to customer"); setReply(""); }

  return <>
    <AdminPageHeader title="Support desk" description="Manage customer conversations, enterprise SLAs, ownership, and technical escalation from one operator queue." actions={<><AdminButton onClick={() => toast.success("Support queue synchronized") }><Inbox />Sync inbox</AdminButton><AdminButton variant="primary" onClick={() => setNewOpen(true)}><Plus />New ticket</AdminButton></>} />
    <div className="adm-stats"><Stat label="Open tickets" value={rows.filter((ticket) => ticket.status === "open").length} change="-4" detail="since yesterday" icon={Headphones} data={[18, 17, 18, 14, 13, 11, 9, 7]} /><Stat label="First response" value="18 min" change="-6 min" detail="median this week" icon={Clock3} data={[28, 26, 24, 22, 20, 19, 18, 18]} /><Stat label="SLA attainment" value="97.8%" change="+1.2%" detail="enterprise tickets" icon={Timer} /><Stat label="Customer satisfaction" value="4.84/5" change="+0.06" detail="218 ratings" icon={LifeBuoy} /></div>
    <div className="adm-grid two">
      <div><div className="adm-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search ticket, customer, or assignee…" /><select className="adm-select" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Any status</option><option value="open">Open</option><option value="pending">Pending</option><option value="closed">Closed</option></select><select className="adm-select" value={priority} onChange={(event) => setPriority(event.target.value)}><option value="all">Any priority</option><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></div><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Conversation</th><th>Priority</th><th>Status</th><th>Customer</th><th>Plan</th><th>Assignee</th><th>SLA / updated</th><th /></tr></thead><tbody>{pagination.rows.map((ticket) => <tr className="clickable" key={ticket.id} onClick={() => setSelectedId(ticket.id)}><td><div className="adm-primary-cell"><span className="adm-cell-icon"><MessageSquareReply /></span><div className="adm-cell-copy"><b>{ticket.subject}</b><small>{ticket.id} · {ticket.messages} messages · {ticket.channel}</small></div></div></td><td><StatusPill status={ticket.priority} /></td><td><StatusPill status={ticket.status} /></td><td>{ticket.customer}</td><td><StatusPill status={ticket.plan === "Enterprise" ? "lime" : ticket.plan === "Pro" ? "info" : "neutral"} label={ticket.plan} noDot /></td><td>{ticket.assignee}</td><td><div className="adm-cell-copy"><b className={ticket.slaMinutes && ticket.slaMinutes < 30 ? "text-red-400" : undefined}>{ticket.slaMinutes ? `${ticket.slaMinutes}m left` : "Met"}</b><small>{relativeTime(ticket.updatedAt)}</small></div></td><td><IconAction label="Open ticket" onClick={(event) => { event.stopPropagation(); setSelectedId(ticket.id); }}><MoreHorizontal /></IconAction></td></tr>)}</tbody></table><Pagination {...pagination} onPage={pagination.setPage} /></div></div>
      <div className="adm-grid"><Panel title="SLA watch" description="Tickets nearest to breach" bodyClassName="flush"><ul className="adm-list">{rows.filter((ticket) => ticket.status !== "closed").sort((a, b) => a.slaMinutes - b.slaMinutes).slice(0, 3).map((ticket) => <li className="adm-list-item" key={ticket.id}><Timer /><div className="adm-list-copy"><b>{ticket.customer}</b><small>{ticket.subject}</small></div><div className="adm-list-meta"><b className={ticket.slaMinutes < 30 ? "text-red-400" : ""}>{ticket.slaMinutes}m</b><small>{ticket.priority}</small></div></li>)}</ul></Panel><Panel title="Team load" description="Open and pending conversations"><div className="adm-kpi-row"><span>Maya Chen</span><span>4 tickets</span></div><div className="adm-kpi-row"><span>Jon Bell</span><span>3 tickets</span></div><div className="adm-kpi-row"><span>Sara Malik</span><span>2 tickets</span></div><div className="adm-kpi-row"><span>Unassigned</span><span className="adm-stat-change down">1 ticket</span></div></Panel><Panel title="Support performance" description="This week"><div className="adm-metric-grid"><div className="adm-metric-box"><span>Resolved</span><b>84</b><small>+12% WoW</small></div><div className="adm-metric-box"><span>Reopened</span><b>3</b><small>3.6% rate</small></div><div className="adm-metric-box"><span>Escalated</span><b>7</b><small>8.3% rate</small></div></div></Panel></div>
    </div>

    <Drawer open={Boolean(selected)} onClose={() => setSelectedId(undefined)} title={selected?.subject ?? "Support ticket"} description={selected ? `${selected.id} · ${selected.customer}` : undefined} footer={selected && <><AdminButton onClick={() => patch(selected.id, { status: selected.status === "closed" ? "open" : "closed" }, selected.status === "closed" ? "Ticket reopened" : "Ticket resolved") }><CheckCircle2 />{selected.status === "closed" ? "Reopen" : "Resolve"}</AdminButton><AdminButton variant="primary" onClick={sendReply}><Send />Send reply</AdminButton></>}>
      {selected && <><div className="flex items-center gap-2 mb-4"><StatusPill status={selected.priority} /><StatusPill status={selected.status} /><StatusPill status={selected.plan === "Enterprise" ? "lime" : "info"} label={selected.plan} noDot /></div><DetailGrid items={[["Customer", selected.customer], ["Channel", selected.channel], ["Assignee", selected.assignee], ["SLA remaining", selected.slaMinutes ? `${selected.slaMinutes} minutes` : "Met"], ["Messages", selected.messages], ["Last update", relativeTime(selected.updatedAt)]]} /><p className="adm-section-label">Conversation</p><div className="adm-list border border-white/10 rounded-md"><div className="adm-list-item items-start"><Avatar name="Customer" /><div className="adm-list-copy"><b>{selected.customer}</b><small className="leading-4 mt-2">We can reproduce this consistently in production. The transfer reaches the final checkpoint, then the connection remains open without committing the remote manifest. Diagnostic bundle is attached.</small></div></div><div className="adm-list-item items-start"><Avatar name={selected.assignee === "Unassigned" ? "Orbit Support" : selected.assignee} /><div className="adm-list-copy"><b>{selected.assignee === "Unassigned" ? "Orbit Support" : selected.assignee}</b><small className="leading-4 mt-2">Thanks—we’re reviewing gateway traces and will update you within the SLA window.</small></div></div></div><p className="adm-section-label">Assignment</p><select className="adm-select w-full" value={selected.assignee} onChange={(event) => patch(selected.id, { assignee: event.target.value }, `Assigned to ${event.target.value}`)}><option>Unassigned</option><option>Maya Chen</option><option>Jon Bell</option><option>Sara Malik</option></select><p className="adm-section-label">Reply</p><textarea className="adm-textarea" value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a customer-facing response…" /><div className="flex items-center justify-between mt-2"><span className="text-[7px] text-zinc-600">Reply will be sent by {selected.channel.toLowerCase()}.</span><AdminButton size="small" variant="ghost" onClick={() => toast.message("Internal note mode enabled")}>Add internal note</AdminButton></div></>}
    </Drawer>

    <Modal open={newOpen} onClose={() => setNewOpen(false)} title="Create support ticket" description="Open a conversation on behalf of a customer." footer={<><AdminButton onClick={() => setNewOpen(false)}>Cancel</AdminButton><AdminButton variant="primary" onClick={() => { setNewOpen(false); toast.success("Support ticket created"); }}><UserCheck />Create ticket</AdminButton></>}><div className="adm-form-grid"><div className="adm-field"><label>Customer</label><select className="adm-select w-full"><option>Acme Engineering</option><option>Northstar Labs</option><option>Polaris Commerce</option><option>Vector Health</option></select></div><div className="adm-field"><label>Priority</label><select className="adm-select w-full"><option>Normal</option><option>High</option><option>Urgent</option><option>Low</option></select></div><div className="adm-field span-2"><label>Subject</label><input className="adm-input" autoFocus placeholder="Brief summary" /></div><div className="adm-field span-2"><label>Initial message</label><textarea className="adm-textarea" placeholder="Describe the customer issue…" /></div></div></Modal>
  </>;
}

export default SupportAdminPage;
