import { LegalDocument, type LegalSection } from "@/components/legal-document";

const sections: LegalSection[] = [
  { title: "Purpose", content: <p>This policy protects customers, their infrastructure, Orbit, and the broader internet. It applies to all use of the web application, API, CLI, workers, terminal, automations, backup system, and integrations.</p> },
  { title: "Authorization is required", content: <><p>Do not access, probe, modify, copy, disrupt, or monitor any server, account, network, file, or service unless you have clear authorization. Credentials, public reachability, or a configuration mistake do not create authorization.</p><p>Security testing requires the asset owner’s permission and must stay within the documented scope and rate limits.</p></> },
  { title: "Prohibited harmful activity", content: <><p>You may not use Orbit to distribute malware, ransomware, destructive payloads, credential stealers, botnets, cryptominers, or tools designed primarily to compromise systems.</p><p>Do not launch denial-of-service activity, indiscriminate scanning, brute force attempts, spam, phishing, credential stuffing, or actions intended to evade security controls or attribution.</p></> },
  { title: "Data and content restrictions", content: <><p>Do not store or transfer content that is unlawful, infringes rights, exploits children, facilitates violence, or violates privacy or confidentiality duties.</p><p>Do not use backup, archive, or transfer features as a general public file distribution service or to defeat third-party storage restrictions.</p></> },
  { title: "Platform integrity", content: <><p>Do not bypass plan limits, rate limits, tenant boundaries, approval checks, host-key verification, audit collection, or other technical safeguards. Do not reverse engineer the service except where law expressly permits it.</p><p>Automated clients must use documented APIs, respect backoff headers, and identify themselves accurately.</p></> },
  { title: "Shared and production environments", content: <><p>Use least-privilege credentials and appropriate approvals for production. Do not knowingly create unsafe shared access, publish credentials, or disable recovery protections in a way that creates unreasonable risk to other people or systems.</p></> },
  { title: "Enforcement", content: <><p>We may investigate credible reports, preserve relevant evidence, rate limit, quarantine jobs, revoke tokens, or suspend resources where reasonably necessary to prevent harm. We aim to use the narrowest effective measure and notify the customer when safe and lawful.</p><p>Serious or repeated violations may result in termination and referral to affected providers or authorities.</p></> },
  { title: "Reporting abuse", content: <p>Report suspected abuse to <a href="mailto:abuse@orbit.dev">abuse@orbit.dev</a>. Include the workspace or request identifier, relevant timestamps, affected hosts, and supporting evidence. Do not include passwords or private keys.</p> },
];

export function AcceptableUsePage() { return <LegalDocument eyebrow="Trust" title="Acceptable Use Policy" summary="Use Orbit to operate systems you are authorized to manage—safely, lawfully, and without harming others." updated="July 19, 2026" sections={sections} />; }
export default AcceptableUsePage;
