import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronRight, Code2, Copy, FileCode2, KeyRound, Search, Server, ShieldCheck, Terminal, Workflow } from "lucide-react";
import { Link } from "react-router-dom";
import { Button, Input } from "@/components/ui";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const sections = [
  { group: "Get started", items: ["Introduction", "Create a workspace", "Connect a server", "Explore remote files", "Make your first safe edit"] },
  { group: "Operate", items: ["Transfer files", "Plan a sync", "Deploy changed files", "Open a terminal", "Create runbooks"] },
  { group: "Recover", items: ["File versions", "Backup schedules", "Restore a snapshot", "Deployment rollback", "Recovery testing"] },
  { group: "Manage", items: ["Members and roles", "Approval policies", "Notifications", "API keys", "Audit exports"] },
];

export function DocsPage() {
  const [query, setQuery] = useState("");
  const [active, setActive] = useState("Introduction");
  const filtered = useMemo(() => sections.map((section) => ({ ...section, items: section.items.filter((item) => item.toLowerCase().includes(query.toLowerCase())) })).filter((section) => section.items.length), [query]);
  const command = `npm install -g @orbit/cli\norbit login\norbit server add`;
  return (
    <div className="mx-auto min-h-[calc(100vh-64px)] max-w-[1500px] lg:grid lg:grid-cols-[230px_minmax(0,1fr)_190px]">
      <aside className="hidden border-r border-white/8 px-4 py-6 lg:block"><label className="relative block"><Search className="absolute left-2.5 top-1/2 size-3 -translate-y-1/2 text-zinc-600" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search docs" className="pl-8 text-[9px]" /></label><nav className="mt-5 space-y-5">{filtered.map((section) => <div key={section.group}><p className="mb-1.5 px-2 text-[8px] font-medium uppercase tracking-wider text-zinc-700">{section.group}</p>{section.items.map((item) => <button key={item} type="button" onClick={() => setActive(item)} className={cn("flex h-7 w-full items-center rounded px-2 text-left text-[9px]", active === item ? "bg-white/[0.06] text-white" : "text-zinc-600 hover:text-zinc-300")}>{item}</button>)}</div>)}</nav></aside>
      <article className="min-w-0 px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><div className="mb-8 flex items-center gap-1.5 text-[8px] text-zinc-600"><span>Docs</span><ChevronRight className="size-3" /><span>Get started</span><ChevronRight className="size-3" /><span className="text-zinc-300">{active}</span></div><div className="max-w-3xl"><p className="text-[9px] uppercase tracking-[0.14em] text-blue-400">Get started</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{active}</h1><p className="mt-5 text-sm leading-7 text-zinc-500">Orbit is a secure server operations workspace for connecting to remote infrastructure, working with files, running transfers and deployments, creating backups, and collaborating with a complete audit trail.</p>
        <div className="mt-8 rounded-lg border border-blue-400/15 bg-blue-400/[0.045] p-4"><div className="flex gap-3"><BookOpen className="mt-0.5 size-4 shrink-0 text-blue-300" /><div><p className="text-[10px] font-medium text-blue-200">This guide uses the Free plan</p><p className="mt-1 text-[9px] leading-4 text-blue-200/55">You can connect two servers, explore files, perform manual transfers, and keep seven days of version history without a credit card.</p></div></div></div>
        <h2 className="mt-10 text-2xl font-semibold">Install the Orbit CLI</h2><p className="mt-3 text-[11px] leading-6 text-zinc-500">The web workspace works without a local install. The CLI is useful for CI, deployment scripts, and importing existing SFTP profiles.</p><div className="mt-4 overflow-hidden rounded-lg border border-white/10 bg-[#101115]"><header className="flex h-9 items-center justify-between border-b border-white/8 px-3 text-[8px] text-zinc-600"><span>Terminal</span><button type="button" onClick={() => void navigator.clipboard.writeText(command).then(() => toast.success("Commands copied"))} className="flex items-center gap-1.5 hover:text-white"><Copy className="size-3" />Copy</button></header><pre className="p-4 text-[10px] leading-6 text-zinc-400">{command}</pre></div>
        <h2 className="mt-10 text-2xl font-semibold">Connect your first server</h2><p className="mt-3 text-[11px] leading-6 text-zinc-500">Open <strong className="text-zinc-300">Servers → Add server</strong>, choose SFTP, and enter a host, port, username, and authentication method. Orbit tests reachability and presents the SSH fingerprint before saving.</p><ol className="mt-5 space-y-3">{["Enter a friendly name and environment.", "Choose password, private key, SSH agent, or a vault reference.", "Verify the server fingerprint against a trusted source.", "Set the allowed root path and test the connection."].map((step, index) => <li key={step} className="flex gap-3 rounded-md border border-white/8 bg-white/[0.018] p-3 text-[10px] text-zinc-400"><span className="grid size-5 shrink-0 place-items-center rounded-full border border-white/10 font-mono text-[8px] text-zinc-500">{index + 1}</span>{step}</li>)}</ol>
        <h2 className="mt-10 text-2xl font-semibold">What happens next</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[Server, "Server workspace", "Health, connection settings, files, transfers, backups, deployments, monitoring, and activity."], [FileCode2, "Remote explorer", "Browse and edit inside the allowed root with atomic saves and file history."], [ShieldCheck, "Safe operations", "Dry-run plans, policies, snapshots, checksums, and clear rollback targets."], [Workflow, "Automation", "Turn repeatable tasks into schedules, webhooks, or approved runbooks."]].map(([Icon, title, text]) => <div key={String(title)} className="rounded-lg border border-white/8 p-4"><Icon className="size-4 text-blue-300" /><h3 className="mt-5 text-sm font-semibold">{String(title)}</h3><p className="mt-2 text-[9px] leading-4 text-zinc-500">{String(text)}</p></div>)}</div>
        <div className="mt-12 flex items-center justify-between border-t border-white/8 pt-6"><span className="text-[9px] text-zinc-600">Was this page helpful? <button className="ml-2 text-zinc-400 hover:text-white">Yes</button> · <button className="text-zinc-400 hover:text-white">No</button></span><button type="button" onClick={() => setActive("Create a workspace")} className="flex items-center gap-2 text-[9px] text-zinc-400 hover:text-white">Next: Create a workspace<ArrowRight className="size-3" /></button></div>
      </div></article>
      <aside className="hidden border-l border-white/8 px-5 py-14 xl:block"><p className="text-[8px] font-medium uppercase tracking-wider text-zinc-700">On this page</p><nav className="mt-3 space-y-2"><a href="#" className="block text-[9px] text-zinc-300">Introduction</a><a href="#" className="block text-[9px] text-zinc-600 hover:text-zinc-300">Install the CLI</a><a href="#" className="block text-[9px] text-zinc-600 hover:text-zinc-300">Connect a server</a><a href="#" className="block text-[9px] text-zinc-600 hover:text-zinc-300">What happens next</a></nav><div className="mt-8 border-t border-white/8 pt-5"><Link to="/api" className="flex items-center gap-2 text-[9px] text-zinc-500 hover:text-white"><Code2 className="size-3" />API reference</Link><Link to="/contact" className="mt-3 flex items-center gap-2 text-[9px] text-zinc-500 hover:text-white"><KeyRound className="size-3" />Get help</Link></div></aside>
    </div>
  );
}

export default DocsPage;
