import { ArrowRight, Building2, Check, CloudCog, Headphones, KeyRound, Network, ScrollText, ShieldCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui";
import { CheckList, MarketingCTA, SectionHeading } from "@/components/marketing";

export function EnterprisePage() {
  return (
    <>
      <section className="marketing-glow px-4 pb-24 pt-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-[9px] font-medium uppercase tracking-[0.15em] text-blue-400">Orbit Enterprise</p><h1 className="mt-6 text-balance text-5xl font-semibold tracking-tight sm:text-6xl">A server control plane your whole organization can govern.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-zinc-500">Standardize infrastructure access across teams and regions without slowing down the people responsible for shipping and recovery.</p><div className="mt-8 flex flex-col gap-2 sm:flex-row"><Link to="/contact?topic=enterprise"><Button size="lg">Talk to an enterprise engineer<ArrowRight /></Button></Link><Link to="/security"><Button size="lg" variant="outline">Review security</Button></Link></div></div><div className="rounded-2xl border border-white/10 bg-[#111216] p-6"><p className="text-[9px] uppercase tracking-wider text-zinc-600">Enterprise control center</p><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-white/8 bg-white/8">{[["2,418", "managed servers"], ["18", "private workers"], ["99.996%", "fleet uptime"], ["100%", "changes audited"]].map(([value, label]) => <div key={label} className="bg-[#121317] p-4"><strong className="text-xl tabular-nums">{value}</strong><p className="mt-1 text-[8px] text-zinc-600">{label}</p></div>)}</div><div className="mt-4 space-y-2">{["Identity synced from Okta", "Production approvals enforced", "EU data boundary healthy", "Recovery objectives verified"].map((item) => <div key={item} className="flex items-center gap-2 rounded-md border border-white/8 p-3 text-[9px] text-zinc-400"><span className="size-1.5 rounded-full bg-emerald-400" />{item}<Check className="ml-auto size-3 text-emerald-400" /></div>)}</div></div></div></section>

      <section className="border-y border-white/8 bg-[#0c0d10] px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-center text-[9px] uppercase tracking-[0.14em] text-zinc-700">Built for global engineering and operations teams</p><div className="mt-8 grid grid-cols-2 gap-6 text-center font-heading text-lg font-semibold text-zinc-600 sm:grid-cols-3 lg:grid-cols-6"><span>Northstar</span><span>Vector</span><span>Polaris</span><span>Monarch</span><span>Juniper</span><span>Aperture</span></div></div></section>

      <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Scale the system, not the risk" title="Enterprise capability without a separate enterprise product." description="Your teams keep the fast workspace. Governance layers cleanly around identity, networking, execution, data, and support." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[
        [Users, "Identity lifecycle", "SAML SSO, OIDC, SCIM, group-to-role mapping, MFA enforcement, session policy, and just-in-time grants."],
        [Network, "Private connectivity", "Customer-hosted workers, VPC peering, static egress, regional routing, bastions, and proxy policy."],
        [KeyRound, "Keys and secrets", "BYOK, KMS integration, Vault references, credential rotation, host-key governance, and recursive redaction."],
        [ShieldCheck, "Custom governance", "Resource-scoped RBAC, approval chains, separation of duties, break-glass controls, and policy as code."],
        [ScrollText, "Audit and compliance", "Immutable logs, SIEM streaming, custom retention, legal hold, evidence exports, and access reviews."],
        [Headphones, "Enterprise success", "24/7 priority support, named technical account lead, onboarding, architecture reviews, and SLA."],
      ].map(([Icon, title, text]) => <article key={String(title)} className="rounded-xl border border-white/10 bg-[#111216] p-6"><Icon className="size-5 text-blue-300" /><h3 className="mt-7 text-lg font-semibold">{String(title)}</h3><p className="mt-3 text-[10px] leading-5 text-zinc-500">{String(text)}</p></article>)}</div></div></section>

      <section className="border-y border-white/8 bg-[#0c0d10] px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-2"><div><SectionHeading eyebrow="Deploy your way" title="SaaS control plane or private execution—credentials stay where policy requires." description="Orbit separates orchestration metadata from remote execution so each organization can choose its trust boundary." /><CheckList className="mt-8" items={["Orbit-hosted regional workers for fast setup", "Customer-managed worker pools inside your VPC", "No inbound firewall rule required", "Encrypted, outbound-only job channel", "Tenant-scoped pools, quotas, and update rings", "Health, capacity, and version management from admin"]} /></div><div className="relative rounded-xl border border-white/10 bg-[#111216] p-6"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-lg border border-blue-400/20 bg-blue-400/5 p-5 text-center"><CloudCog className="mx-auto size-5 text-blue-300" /><p className="mt-3 text-[10px] font-medium">Orbit control plane</p><p className="mt-1 text-[8px] text-zinc-600">Policy · jobs · audit</p></div><ArrowRight className="size-4 text-zinc-700" /><div className="rounded-lg border border-emerald-400/20 bg-emerald-400/5 p-5 text-center"><Building2 className="mx-auto size-5 text-emerald-300" /><p className="mt-3 text-[10px] font-medium">Your private worker</p><p className="mt-1 text-[8px] text-zinc-600">Secrets · network · SSH</p></div></div><div className="mx-auto my-4 h-10 w-px border-l border-dashed border-white/15" /><div className="mx-auto max-w-xs rounded-lg border border-white/10 bg-black/20 p-4 text-center"><Network className="mx-auto size-4 text-zinc-400" /><p className="mt-2 text-[9px] font-medium">Private server fleet</p><p className="mt-1 text-[7px] text-zinc-600">No credentials or file content cross the boundary</p></div></div></div></section>

      <section className="px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading align="center" eyebrow="A deliberate rollout" title="From evaluation to production in weeks, not quarters." /><div className="mt-12 grid gap-4 lg:grid-cols-4">{[["01", "Discover", "Map teams, server inventory, access paths, policies, and recovery requirements."], ["02", "Pilot", "Import a representative workspace and validate private connectivity and workflows."], ["03", "Govern", "Connect identity, roles, approvals, audit exports, retention, and security monitoring."], ["04", "Scale", "Roll out by team or environment with training, metrics, and a named success plan."]].map(([number, title, text]) => <article key={title} className="rounded-xl border border-white/10 bg-[#111216] p-5"><span className="font-mono text-[8px] text-zinc-700">{number}</span><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-3 text-[10px] leading-5 text-zinc-500">{text}</p></article>)}</div></div></section>
      <MarketingCTA title="Design your enterprise server workspace with us." description="Bring your architecture, security, and operations teams. We’ll map Orbit to your network, identity, governance, and recovery model." primary="Schedule an architecture session" />
    </>
  );
}

export default EnterprisePage;
