import { LegalDocument, type LegalSection } from "@/components/legal-document";

const sections: LegalSection[] = [
  { title: "Agreement and eligibility", content: <><p>These Terms govern access to Orbit’s websites, applications, APIs, command-line tools, private workers, support, and related services. By creating an account or using the service, you agree to them on behalf of yourself and, where applicable, your organization.</p><p>You must be able to form a binding contract and be authorized to accept these Terms for the organization whose infrastructure you connect.</p></> },
  { title: "Accounts and workspaces", content: <><p>You are responsible for accurate account information, protecting authentication factors, reviewing workspace membership, and promptly revoking access that is no longer required.</p><p>Workspace owners control server connections, member roles, retention settings, integrations, billing, and organization data. Orbit may rely on owner instructions as authorized instructions from the customer.</p></> },
  { title: "Authorized infrastructure use", content: <><p>You may connect only servers, networks, files, accounts, and systems that you own or are expressly authorized to administer. You must comply with applicable laws, third-party agreements, and the Acceptable Use Policy.</p><p>You are responsible for reviewing dry-run plans, remote paths, commands, automation rules, backup scope, and restore targets before execution.</p></> },
  { title: "Service plans and billing", content: <><p>Free, Pro, and Enterprise plans include the entitlements shown on the pricing page or order form. Paid subscriptions renew for the selected interval until canceled. Fees are exclusive of taxes unless stated otherwise.</p><p>We will provide notice before materially reducing a paid plan’s core entitlements. Usage overages, if enabled, are calculated from auditable workspace records.</p></> },
  { title: "Customer data and credentials", content: <><p>You retain ownership of connection metadata, files, commands, backups, audit records, and other content submitted through the service. You grant Orbit the limited rights necessary to host, transmit, process, protect, and support that data.</p><p>Server credentials are processed only to perform authorized operations. Secret fields are encrypted and excluded from customer-facing responses and ordinary application logs.</p></> },
  { title: "Security responsibilities", content: <><p>Orbit maintains administrative, technical, and organizational safeguards appropriate to the service. No online system is risk-free. You remain responsible for server hardening, credential scope, backups appropriate to your recovery objectives, and verifying high-risk operations.</p><p>Report suspected compromise promptly to security@orbit.dev and preserve relevant audit evidence.</p></> },
  { title: "Availability and changes", content: <><p>We work to keep the service reliable and will communicate material incidents through the status page. Maintenance, network providers, customer infrastructure, emergency security measures, or events beyond reasonable control may affect availability.</p><p>Beta features may change and are provided without a production availability commitment unless an order form says otherwise.</p></> },
  { title: "Suspension and termination", content: <><p>We may limit or suspend access where reasonably necessary to prevent harm, respond to unlawful use, address a security incident, or resolve overdue payment. When practical, we will give notice and an opportunity to cure.</p><p>You may cancel at any time. Following termination, export and deletion are handled under the applicable plan, order form, and privacy documentation.</p></> },
  { title: "Warranties and liability", content: <><p>To the extent permitted by law, the service is provided as available and implied warranties are disclaimed. Neither party is liable for indirect, special, incidental, consequential, or punitive damages, or lost profits, revenues, goodwill, or data.</p><p>Except for obligations that cannot legally be limited, each party’s aggregate liability is limited to fees paid or payable for the service during the twelve months preceding the event giving rise to the claim.</p></> },
  { title: "General terms", content: <><p>Order forms, the Data Processing Addendum, the Privacy Policy, and the Acceptable Use Policy form part of the agreement where applicable. If terms conflict, an executed order form controls for that transaction.</p><p>Neither party may assign the agreement without consent, except in connection with a merger, acquisition, or sale of substantially all assets. Notices may be delivered electronically. If one provision is unenforceable, the remainder continues in effect.</p></> },
];

export function TermsPage() { return <LegalDocument eyebrow="Legal" title="Terms of Service" summary="The rules that make Orbit a dependable place to operate shared infrastructure." updated="July 19, 2026" sections={sections} />; }
export default TermsPage;
